# -*- coding: utf-8 -*-
"""10814.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xbu4gNbSWTxFo7tbaKM7tWI_wDYPG4yu
"""

#2차원 배열에서 가입순은 입력 순이니까 가장 작은 나이 먼저 찾고 remove. 
#중복되는거 있으면 차피 min은 인덱스 빠른걸 찾아주기때문에 상관없음

n=int(input())
member_list=[list(map(str, input().split())) for _ in range(n)]

age = [i[0] for i in member_list]
#age = list(zip(*member_list))[0]
print(age[1])

'''idx=0

for i in range(n):
  idx=index(min(age))
  del age[idx]
  del member_lso'''

