# -*- coding: utf-8 -*-
"""10825.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/154P9FXm_Z7DRvuFeWGWqeS6PMvpIYTsI
"""

#문제가 드러움

inf=-9

N=int(input())
#score = [list(input().split()) for _ in range(N)]
list_score=[[],[],[],[]]
for j in range(N):
  score = list(input().split()) 
  for i in range(4):
    list_score[i].append(score[i])

print(list_score)
score2=list_score
score_index=[]
ind=0

def array(i):
  while(1):
    max_val = max(list_score[i])
    max_ind = list_score[i].index(max_val)
    score_index.append(max_ind)
    if (len(list_score)>1 and score2[i][score_index[ind-1]] == max_val):
      array(i+1)

    for i in range(3):
      list_score[i][max_ind]=inf
    ind+=1

N=int(input())
score = [[0 for _ in range(4)] for _ in range(N)]
print(score)

