# -*- coding: utf-8 -*-
"""1543.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jV6FSYgecJKi8iTVX4mwMahXkXWX7Rlj
"""

ss=input()
qq=input()
cnt=0
ind=0

while(1):
  if (qq in ss[ind:]):
    #ss=ss.replace(qq,"",1)#이건 배열을 계속 바꿔가면서 하니까 배열 바뀔때 qq랑 같은게 생길 수 있음
    ind=ind + ss[ind:].index(qq) + len(qq)
    print(ind)
    cnt+=1
  else:
    break 

print(cnt)