# -*- coding: utf-8 -*-
"""15904.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qFYsIM_LjLGxZweNT08x4v1zsyRnRT9T
"""

string=input()
arr=['U','C','P','C']

def loha():
  j=0
  for i in range(len(string)):
    if (string[i]==arr[j]):
      j+=1
    if (j==4):
      return j
  return j
  
p=loha()
if (p==4):
  print("I love UCPC")
else:
  print("I hate UCPC")

