# -*- coding: utf-8 -*-
"""1978.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dNjR-XOp8KEgocYHDh_ZXbQM9bCge8Vs
"""

def prim_num(n):
  if(n==0 or n==1):
    return 0
  for i in range(2,n):
    if((n%i)==0):
      return 0
  return 1


a=int(input())
num=list(map(int, input().split()))

cnt=0
for i in range(a):
  if(prim_num(num[i])):
    cnt=cnt+1

print(cnt)

