# -*- coding: utf-8 -*-
"""1991.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ALEsqMUlhwTFO3For2X94JX1ohSnSDht
"""

#나중에 완성하기
n=int(input())
tree=[]
for i in range(n):
  arr = list(input().split())
  tree.append(arr)
  tree[i][0] = ord(tree[i][0]) - 65
  tree[i][1] = ord(tree[i][1]) - 65 #B=1, c=2 ... 을 만들어주기
  tree[i][2] = ord(tree[i][2]) - 65

print(tree)

def first_(node):
  print(chr(node[0]+65),end='')
  if (node[1] != -19):
    first_(tree[node[1]])
  if (node[2] != -19):
    first_(tree[node[2]])


first_(tree[0])

