# -*- coding: utf-8 -*-
"""2217.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18B5B_IhXKOeE-ODincS39FPZFESxaHES
"""

a=int(input())
rope=[int(input()) for i in range(a)]

max=0
for i in range(a,0,-1):
  if(max<min(rope)*i):
    max=min(rope)*i
  rope.remove(min(rope))
  print(rope)

print(max)

