# -*- coding: utf-8 -*-
"""2839.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19DHRoodd_BMVTrecZ06XQZcdM2ywbzOw
"""

n=int(input())
sum=0


def mini(n):
  if (n==3):
    return 1
  if (n==4):
    return -1
  if (n%5 == 0):
    sum=n//5
    return sum

  min=9999
  for i in range(n//5+1):
    if ((n-(i*5)) % 3 == 0):
      sum=i + (n-(i*5))//3
      if (sum < min):
        min=sum
  if (min==9999): return -1
  else: return min

#4를 제외한 모든 수가 -1될 수는 없음!!! 다 5와 3으로 나눠진다.

print(mini(n))

