# -*- coding: utf-8 -*-
"""3009.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QWUUzeyIk3rsShUb8qTR4lxnhkDgW7NA
"""

aa=[]
bb=[]
for i in range(3):
  a,b = map(int, input().split())
  aa.append(a)
  bb.append(b)

for i in range(3):
  if(aa.count(aa[i])==1):
    print(aa[i], end=' ')

for i in range(3):
  if(bb.count(bb[i])==1):
    print(bb[i])

