# -*- coding: utf-8 -*-
"""5585.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jVsEKACD6KZljkDwqxlNfjPTSkPY07IP
"""

coin_num=[0 for i in range(6)]
coin_array=[500,100,50,10,5,1]

def cooo(rest, coin):
    num=int(rest/coin)
    rest1=rest-(num*coin)
    return num, rest1

cost=int(input()) 
rest=1000-cost
j=0
for i in coin_array:
    coin_num[j], rest = cooo(rest,i)
    j=j+1

print(sum(coin_num))

